tomahawk
    marketid
    final_potacv_for_sl_exclusive
    final_potacv_for_da_exclusive
    final_potacv_for_sl_blocks
    final_potacv_for_da_blocks
    sl_total_block_recommendation
    sl_total_released
    sl_total_sold
    sl_total_sold_perc
    sl_organic_block_recommendation
    sl_organic_released
    sl_organic_sold
    sl_organic_sold_perc
    sl_sem_block_recommendation
    sl_sem_released
    sl_sem_sold
    sl_sem_sold_perc
    da_total_block_recommendation
    da_total_released
    da_total_sold
    da_total_sold_perc
    da_organic_block_recommendation
    da_organic_released
    da_organic_sold
    da_organic_sold_perc
    da_sem_block_recommendation
    da_sem_released
    da_sem_sold
    da_sem_sold_perc
    sl_business_rule
    da_business_rule
    sl_review_reason
    da_review_reason
    backorder_sl_blocks
    backorder_da_blocks
    backorder_date
    blockprice
    current_exclusiveprice
    sl_exclusive_price_recommended
    da_exclusive_price_recommended
    prerules_sl_price_recommendation
    sl_fit_adjusted
    sl_lower
    sl_upper
    runrate_sl_forecast
    sl_acv_to_use
    potential_sem_sl_acv
    da_fit_adjusted
    da_lower
    da_upper
    runrate_da_forecast
    da_acv_to_use
    potential_sem_da_acv
    sl_advertiser_count
    sl_max_advertiser_acv
    da_advertiser_count
    da_max_advertiser_acv
    sl_acv_other_month_3
    sl_acv_other_month_2
    sl_acv_other_month_1
    sl_acv_other_yesterday
    sl_acv_sem_month_3
    sl_acv_sem_month_2
    sl_acv_sem_month_1
    sl_acv_sem_yesterday
    sl_potential_acv_other_month_3
    sl_potential_acv_other_month_2
    sl_potential_acv_other_month_1
    sl_potential_acv_other_yesterday
    sl_potential_acv_sem_month_3
    sl_potential_acv_sem_month_2
    sl_potential_acv_sem_month_1
    sl_potential_acv_sem_yesterday
    sl_imps_other_month_3
    sl_imps_other_month_2
    sl_imps_other_month_1
    sl_imps_other_yesterday
    sl_imps_sem_month_3
    sl_imps_sem_month_2
    sl_imps_sem_month_1
    sl_imps_sem_yesterday
    sl_potential_imps_other_month_3
    sl_potential_imps_other_month_2
    sl_potential_imps_other_month_1
    sl_potential_imps_other_yesterday
    sl_potential_imps_sem_month_3
    sl_potential_imps_sem_month_2
    sl_potential_imps_sem_month_1
    sl_potential_imps_sem_yesterday
    sl_clicks_other_month_3
    sl_clicks_other_month_2
    sl_clicks_other_month_1
    sl_clicks_other_yesterday
    sl_clicks_sem_month_3
    sl_clicks_sem_month_2
    sl_clicks_sem_month_1
    sl_clicks_sem_yesterday
    da_acv_other_month_3
    da_acv_other_month_2
    da_acv_other_month_1
    da_acv_other_yesterday
    da_acv_sem_month_3
    da_acv_sem_month_2
    da_acv_sem_month_1
    da_acv_sem_yesterday
    da_potential_acv_other_month_3
    da_potential_acv_other_month_2
    da_potential_acv_other_month_1
    da_potential_acv_other_yesterday
    da_potential_acv_sem_month_3
    da_potential_acv_sem_month_2
    da_potential_acv_sem_month_1
    da_potential_acv_sem_yesterday
    da_imps_other_month_3
    da_imps_other_month_2
    da_imps_other_month_1
    da_imps_other_yesterday
    da_imps_sem_month_3
    da_imps_sem_month_2
    da_imps_sem_month_1
    da_imps_sem_yesterday
    da_potential_imps_other_month_3
    da_potential_imps_other_month_2
    da_potential_imps_other_month_1
    da_potential_imps_other_yesterday
    da_potential_imps_sem_month_3
    da_potential_imps_sem_month_2
    da_potential_imps_sem_month_1
    da_potential_imps_sem_yesterday
    da_clicks_other_month_3
    da_clicks_other_month_2
    da_clicks_other_month_1
    da_clicks_other_yesterday
    da_clicks_sem_month_3
    da_clicks_sem_month_2
    da_clicks_sem_month_1
    da_clicks_sem_yesterday
    process_date
