hist_market_intelligence_detail
    ad_market_id
    state
    county
    ad_region
    parent_sp
    specialty
    market_type
    sl_inventory_type
    sl_inventory
    sl_price
    sl_subscription_price
    sl_value
    sl_sold_inventory
    sl_sold_value
    sl_revenue
    da_inventory_type
    da_inventory
    da_price
    da_value
    da_sold_inventory
    da_sold_value
    da_revenue
    ad_revenue
    sl_unsold_inventory
    sl_unsold_value
    sl_sell_through
    sl_revenue_opportunity
    sl_monetization
    sl_monetization_status
    da_unsold_inventory
    da_unsold_value
    da_sell_through
    da_revenue_opportunity
    da_monetization
    da_monetization_status
    ad_value
    ad_sold_value
    ad_unsold_value
    ad_revenue_opportunity
    ad_sell_through
    ad_monetization
    ad_monetization_status
    market_size
    county_state_psp
    lawyer_cnt
    potential_lawyer_cnt
    lawyer_claimed_cnt
    claim_rate
    potential_claim_rate
    county_claim_rate
    sl_value_per_claim_lawyer
    da_value_per_claim_lawyer
    ad_value_per_claim_lawyer
    top_claim_rate
    top_sl_value_per_claim_lawyer
    top_ad_value_per_claim_lawyer
    top_da_value_per_claim_lawyer
    sl_market_segment
    da_market_segment
    ad_market_segment
    etl_load_date
    year_month
