mrr_customer_category_all_products
    customer_id
    yearmonth
    mrr_customer_category
    mrr_current_advertisement
    mrr_current_avvopro
    mrr_current_ignite
    mrr_current_website
    mrr_current_adplacement
    mrr_current_total
    mrr_prior_advertisement
    mrr_prior_avvopro
    mrr_prior_ignite
    mrr_prior_website
    mrr_prior_adplacement
    mrr_prior_total
    revenue_current_advertisement
    revenue_current_avvopro
    revenue_current_ignite
    revenue_current_website
    revenue_current_misc
    revenue_current_adplacement
    revenue_current_total
    revenue_prior_advertisement
    revenue_prior_avvopro
    revenue_prior_ignite
    revenue_prior_website
    revenue_prior_misc
    revenue_prior_adplacement
    revenue_prior_total
    mrr_acquired
    mrr_penetrated
    mrr_downsized
    mrr_churned
    mrr_retained
    mrr_returned
    expired_date
    expired_reason
    block_conversion_flag
    refund_current_month_flag
    customer_prev_billed_date
    customer_billed_current_month_flag
    promo_flag
