professional_dimension
    professional_id
    professional_prefix
    professional_first_name
    professional_middle_name
    professional_last_name
    professional_suffix
    professional_gender_name
    professional_email_address_name
    professional_website_url
    professional_claim_number
    professional_claim_date
    professional_claim_method_name
    professional_name
    industry_name
    professional_alias_name
    professional_phone_number_1
    professional_phone_number_2
    professional_phone_number_3
    professional_address_1_line_1
    professional_address_1_line_2
    professional_city_name_1
    professional_county_name_1
    professional_state_name_1
    professional_country_name_1
    professional_postal_code_1
    professional_address_2_line_1
    professional_address_2_line_2
    professional_city_name_2
    professional_county_name_2
    professional_state_name_2
    professional_country_name_2
    professional_postal_code_2
    professional_address_3_line_1
    professional_address_3_line_2
    professional_city_name_3
    professional_county_name_3
    professional_state_name_3
    professional_country_name_3
    professional_postal_code_3
    professional_license_state_name_1
    professional_license_state_name_2
    professional_license_state_name_3
    professional_avvo_rating
    professional_practice_indicator
    professional_delete_indicator
    professional_user_account_id
    professional_address_state_code_1
    professional_address_state_code_2
    professional_address_state_code_3
    source_system_update_datetime
    record_flag